language: c

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: osx
      compiler: clang
      osx_image: xcode11
    - os: osx
      compiler: clang
      osx_image: xcode9.4
    - os: osx
      compiler: clang
      osx_image: xcode7.3
 
script:
  - make all test_programs && cat benchmark | ./benchmark &&  ./test_slow_decompression
